# Generated by Django 4.2.28 on 2026-02-18 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Receta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_prescripcion', models.DateTimeField(default=django.utils.timezone.now)),
                ('notas', models.TextField(blank=True)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='recetas', to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='recetas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha_prescripcion'],
            },
        ),
        migrations.CreateModel(
            name='Medicamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('forma', models.CharField(blank=True, max_length=60)),
                ('concentracion', models.CharField(blank=True, max_length=60)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='DetalleReceta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('dosis', models.CharField(max_length=120)),
                ('frecuencia', models.CharField(max_length=120)),
                ('duracion_dias', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('instrucciones', models.TextField(blank=True)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('medicamento', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='recetas', to='recetas.medicamento')),
                ('receta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='detalles', to='recetas.receta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
