# Generated by Django 4.2.28 on 2026-02-18 04:16

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TipoExamen',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('categoria', models.CharField(choices=[('LAB', 'Laboratorio'), ('GAB', 'Gabinete')], max_length=3)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ExamenPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_solicitud', models.DateField()),
                ('fecha_resultado', models.DateField(blank=True, null=True)),
                ('resultado_texto', models.TextField(blank=True)),
                ('adjunto', models.FileField(blank=True, null=True, upload_to='examenes/')),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='examenes', to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='examenes', to='pacientes.paciente')),
                ('tipo_examen', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='examenes', to='examenes.tipoexamen')),
            ],
            options={
                'ordering': ['-fecha_solicitud'],
            },
        ),
    ]
