# Generated by Django 4.2.28 on 2026-02-18 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Consulta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_visita', models.DateTimeField(default=django.utils.timezone.now)),
                ('motivo_consulta', models.TextField(blank=True)),
                ('subjetivo', models.TextField(blank=True)),
                ('evaluacion', models.TextField(blank=True)),
                ('plan', models.TextField(blank=True)),
                ('diagnostico_texto', models.TextField(blank=True)),
                ('diagnostico_codigos', models.CharField(blank=True, max_length=255)),
                ('estatus', models.CharField(choices=[('ABIERTA', 'Abierta'), ('CERRADA', 'Cerrada')], default='ABIERTA', max_length=10)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='consultas', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha_visita'],
            },
        ),
        migrations.CreateModel(
            name='ExamenFisico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perimetro_cefalico_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('temperatura_c', models.DecimalField(blank=True, decimal_places=1, max_digits=4, null=True, validators=[django.core.validators.MinValueValidator(30), django.core.validators.MaxValueValidator(45)])),
                ('frecuencia_cardiaca_lpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('frecuencia_respiratoria_rpm', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presion_sistolica', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('presion_diastolica', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('saturacion_oxigeno_pct', models.PositiveSmallIntegerField(blank=True, null=True, validators=[django.core.validators.MaxValueValidator(100)])),
                ('notas', models.TextField(blank=True)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='examen_fisico', to='consultas.consulta')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
