# Generated by Django 4.2.28 on 2026-02-18 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Hito',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=160)),
                ('edad_min_dias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_max_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('dominio', models.CharField(choices=[('MOTOR', 'Motor'), ('LENGUAJE', 'Lenguaje'), ('SOCIAL', 'Social'), ('COGNITIVO', 'Cognitivo')], max_length=10)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='HitoPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_logro', models.DateField(blank=True, null=True)),
                ('notas', models.TextField(blank=True)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('hito', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pacientes', to='desarrollo.hito')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hitos', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha_logro'],
            },
        ),
    ]
