# Generated by Django 4.2.28 on 2026-02-18 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ReferenciaCrecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('sexo', models.CharField(choices=[('M', 'Masculino'), ('F', 'Femenino'), ('X', 'Otro/No especificado')], max_length=1)),
                ('edad_dias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('metrica', models.CharField(choices=[('PESO', 'Peso'), ('TALLA', 'Talla'), ('PC', 'Perimetro cefalico')], max_length=5)),
                ('l', models.DecimalField(decimal_places=3, max_digits=6)),
                ('m', models.DecimalField(decimal_places=3, max_digits=6)),
                ('s', models.DecimalField(decimal_places=3, max_digits=6)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['sexo', 'edad_dias', 'metrica'],
            },
        ),
        migrations.CreateModel(
            name='MedicionCrecimiento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('fecha_medicion', models.DateField()),
                ('peso_kg', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('talla_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('perimetro_cefalico_cm', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True)),
                ('edad_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('edad_corregida_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('tipo_edad', models.CharField(choices=[('CRONO', 'Cronologica'), ('CORR', 'Corregida')], default='CRONO', max_length=5)),
                ('percentil_peso', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percentil_talla', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percentil_imc', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('percentil_perimetro', models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)])),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mediciones', to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mediciones', to='pacientes.paciente')),
            ],
            options={
                'ordering': ['-fecha_medicion'],
            },
        ),
    ]
