# Generated by Django 4.2.28 on 2026-02-20 01:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crecimiento', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='clasificacion',
            field=models.CharField(blank=True, max_length=60),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='imc',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='indicador',
            field=models.CharField(choices=[('PESO_EDAD', 'Peso para la edad'), ('TALLA_EDAD', 'Talla para la edad'), ('IMC_EDAD', 'IMC para la edad')], default='TALLA_EDAD', max_length=16),
        ),
        migrations.AddField(
            model_name='medicioncrecimiento',
            name='z_score',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=6, null=True),
        ),
        migrations.AlterField(
            model_name='referenciacrecimiento',
            name='metrica',
            field=models.CharField(choices=[('PESO', 'Peso'), ('TALLA', 'Talla'), ('PC', 'Perimetro cefalico'), ('IMC', 'Indice de masa corporal')], max_length=5),
        ),
    ]
