# Generated by Django 4.2.28 on 2026-02-18 04:16

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('pacientes', '0001_initial'),
        ('consultas', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('nombre', models.CharField(max_length=120)),
                ('fabricante', models.CharField(blank=True, max_length=120)),
                ('codigo', models.CharField(blank=True, max_length=60)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='VacunacionPaciente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('numero_dosis', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('fecha_aplicacion', models.DateField()),
                ('lote', models.CharField(blank=True, max_length=80)),
                ('sitio', models.CharField(blank=True, max_length=80)),
                ('notas', models.TextField(blank=True)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('consulta', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='vacunaciones', to='consultas.consulta')),
                ('paciente', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacunaciones', to='pacientes.paciente')),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='aplicaciones', to='inmunizaciones.vacuna')),
            ],
            options={
                'ordering': ['-fecha_aplicacion'],
            },
        ),
        migrations.CreateModel(
            name='EsquemaVacuna',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('creado_en', models.DateTimeField(auto_now_add=True)),
                ('actualizado_en', models.DateTimeField(auto_now=True)),
                ('esta_borrado', models.BooleanField(default=False)),
                ('borrado_en', models.DateTimeField(blank=True, null=True)),
                ('numero_dosis', models.PositiveSmallIntegerField(validators=[django.core.validators.MinValueValidator(1)])),
                ('edad_min_dias', models.PositiveIntegerField(validators=[django.core.validators.MinValueValidator(0)])),
                ('edad_max_dias', models.PositiveIntegerField(blank=True, null=True)),
                ('borrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_borrados', related_query_name='%(app_label)s_%(class)s_borrado', to=settings.AUTH_USER_MODEL)),
                ('vacuna', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='esquemas', to='inmunizaciones.vacuna')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
